### ISSUE TITLE
SNS Publish missing from IAM permissions 

### ISSUE THREAD

**Issue by csol01** [QuiNovas/terraform-aws-config#10]
Hi All,

I've just picked up a small piece of work where they've used your module to spin up a load of AWS Config rule, everything works great with the exception of the SNS notifications that never get sent because the recorder role doesn't container the sns:Publish permission for the sns topic the module creates. I'm going to work around it myself for now using datasources, but it might be worth a module update at some point.

**Comment by vchinnakotla** [comment]
Added the missing permission in release 3.0.3
